src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
class Users
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Le nom est obligatoire')]
    private ?string $nom = null;


    
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Le prenom est obligatoire')]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"L'email est obligatoire")]
    #[Assert\Email(
        message: 'The email {{ value }} is not a valid email.',
    )]
    
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"L'adresse est obligatoire")]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'La ville est obligatoire')]
    private ?string $ville = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Le code Pastal est obligatoire')]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Le pays est obligatoire')]
    private ?string $pays = null;

    

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Le Status est obligatoire')]
    private ?string $etat = null;

   
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Username est obligatoire')]
    #[Assert\Length(
        min: 2,
        max: 20,
        minMessage: ' username doit contenir au moins  {{ limit }} caracteres ',
        maxMessage: ' username doit contenir au plus {{ limit }} caracteres',
    )]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Password est obligatoire')]

    #[Assert\Length(
        min: 2,
        max: 20,
        minMessage: ' Password doit contenir au moins  {{ limit }} caracteres ',
        maxMessage: ' Password doit contenir au plus {{ limit }} caracteres',
    )]
    private ?string $password = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\ManyToMany(targetEntity: Roles::class, inversedBy: 'users')]
    private Collection $role;

    public function __construct()
    {
        $this->role = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

  

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, roles>
     */
    public function getRole(): Collection
    {
        return $this->role;
    }

    public function addRole(roles $role): self
    {
        if (!$this->role->contains($role)) {
            $this->role->add($role);
        }

        return $this;
    }

    public function removeRole(roles $role): self
    {
        $this->role->removeElement($role);

        return $this;
    }
}

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use App\Entity\Roles;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('nom')
            ->add('prenom')
            ->add('telephone')
            ->add('email')
            ->add('adresse')
            ->add('ville')
            ->add('code_postal')
            ->add('pays')
            ->add('etat', ChoiceType::class, [
                'choices'  => [
                    'actif' => 'actif',
                    'inactif' => 'inactif',
                ],
                'expanded' => true, // displays the options as radio buttons
                'multiple' => false, // allows only one option to be selected
            ])
           // ->add('etat')
            ->add('username')
            ->add('password')
            ->add('created_at')
            ->add('updated_at')
            
            ->add('role', EntityType::class, [
                'class' => Roles::class,
                'choice_label' => 'nom',
                'placeholder'=>'choisir un role',
                'multiple' => true,
                'expanded' => false,
                'attr' => ['class' => 'form-control'],
            ]);
                       
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
            'cascade_validation' => true,
        ]);
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use App\Repository\UsersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/users')]
class UsersController extends AbstractController
{
    #[Route('/', name: 'app_users_index', methods: ['GET'])]
    public function index(UsersRepository $usersRepository): Response
    {
        return $this->render('users/index.html.twig', [
            'users' => $usersRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_users_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UsersRepository $usersRepository): Response
    {
        $user = new Users();
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $usersRepository->save($user, true);

            return $this->redirectToRoute('app_users_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('users/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_users_show', methods: ['GET'])]
    public function show(Users $user): Response
    {
        return $this->render('users/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_users_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Users $user, UsersRepository $usersRepository): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $usersRepository->save($user, true);

            return $this->redirectToRoute('app_users_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('users/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_users_delete', methods: ['POST'])]
    public function delete(Request $request, Users $user, UsersRepository $usersRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $usersRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_users_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/users/_delete_form.html.twig
<form method="post" action="{{ path('app_users_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/users/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
<table>
        <tr>
                <td> {{ form_label(form, "Nom",{'attr': { 'style': 'color: blue;'}}) }} </td>
                <td>  {{ form_widget(form.nom, { 'attr': {'class': 'foo'} }) }} </td>  
                <td> {{ form_errors(form.nom) }} </td>
                        
        </tr>
        <tr>
                <td> {{ form_label(form,"Prenom")  }} </td>
                <td>  {{ form_widget(form.prenom) }} </td>  
                <td> {{ form_errors(form.prenom) }} </td>
        </tr>

        <tr>
                <td> {{ form_label(form,"Email")  }} </td>
                <td>  {{ form_widget(form.email) }} </td>  
                <td> {{ form_errors(form.email) }} </td>
        </tr>
        <tr>
                <td> {{ form_label(form,"Telephone")  }} </td>
                <td>  {{ form_widget(form.telephone) }} </td>  
                <td> {{ form_errors(form.telephone) }} </td>
        </tr>
        <tr>
                <td> {{ form_label(form,"Adresse")  }} </td>
                <td>  {{ form_widget(form.adresse) }} </td>  
                <td> {{ form_errors(form.adresse) }} </td>
        </tr>
        <tr>
                <td> {{ form_label(form,"Ville")  }} </td>
                <td>  {{ form_widget(form.ville) }} </td>  
                <td> {{ form_errors(form.ville) }} </td>
        </tr>

        <tr>
                <td> {{ form_label(form,"Code Postal")  }} </td>
                <td>  {{ form_widget(form.code_postal) }} </td>  
                <td> {{ form_errors(form.code_postal) }} </td>
        </tr>

        <tr>
                <td> {{ form_label(form,"Pays")  }} </td>
                <td>  {{ form_widget(form.pays) }} </td>  
                <td> {{ form_errors(form.pays) }} </td>
        </tr>
        <tr>
                <td> {{ form_label(form,"Etat")  }} </td>
                <td>
                        {{ form_widget(form.etat, {'attr': {'class': 'form-control'}, 'label_attr': {'class': 'form-check-label radio-inline'}, 'widget_type': 'inline'}) }}
                </td>

                <td> {{ form_errors(form.etat) }} </td>

        </tr>
        
        <tr>
                <td>
                 {{ form_label(form,"Role")  }} </td>
                <td>
                        {{ form_widget(form.role, {'attr': {'class': 'form-control custom-select'}, 'widget_type': 'choice'}) }}

                 </td>
                <td> {{ form_errors(form.role) }} </td>
        </tr>
        <tr>
                <td> {{ form_label(form,"Username")  }} </td>
                <td>  {{ form_widget(form.username) }} </td>  
                <td> {{ form_errors(form.username) }} </td>
        </tr>
        <tr>
                <td> {{ form_label(form,"Password")  }} </td>
                <td>  {{ form_widget(form.password) }} </td>  
                <td> {{ form_errors(form.password) }} </td>
        </tr>
       <tr>
                <td> {{ form_label(form,"CreatedAt")  }} </td>
                <td>  {{ form_widget(form.created_at) }} </td>  
                <td> {{ form_errors(form.created_at) }} </td>
        </tr>
        <tr>
                <td> {{ form_label(form,"UpdateAt")  }} </td>
                <td>  {{ form_widget(form.updated_at) }} </td>  
                <td> {{ form_errors(form.updated_at) }} </td>
        </tr>
        
</table>
   
    <br>
    <button class="btn btn-success btn-lg"><i class="fa fa-download"></i>{{ button_label|default(' Save') }}</button> 
    <a class="btn btn-primary btn-lg" href="{{ path('app_users_index') }}"><i class="fa fa-home"></i> back</a>

{{ form_end(form) }}

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Users{% endblock %}

{% block body %}
    <h1>Edit Users</h1>
        {{ include('users/_form.html.twig') }}

    {{ form_end(form) }}
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users index{% endblock %}

{% block body %}
    <h1>Users index</h1>
    <div>
        <a class="btn btn-success float-right" href="{{ path('app_users_new') }}"><i class="fa fa-plus" aria-hidden="true"></i> Add User</a>
        <input type="text" id="searchField" onkeyup="searchTable()" placeholder="Search...">
    </div>
    <br>
    <table class="table table-bordered border-primary table-striped">
         <thead style= "background: lightblue";>
            <tr style="color:black">
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Telephone</th>
                <th>Email</th>
                <th>Adresse</th>
                <th>Ville</th>
                <th>Code_postal</th>
                <th>Pays</th>
                <th>Etat</th>
                <th>Role</th>
                <th>Username</th>
                <th>Password</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.telephone }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.adresse }}</td>
                <td>{{ user.ville }}</td>
                <td>{{ user.codePostal }}</td>
                <td>{{ user.pays }}</td>
                <td>{{ user.etat }}</td>
                
                <td>
                    {% for role in user.role %}
                        {{ role.nom }}
                    {% endfor %}
                </td>

                <td>{{ user.username }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                
                <td>

                    <a class="btn btn-success" href="{{ path('app_users_show', {'id': user.id}) }}"><i class="fa fa-eye" aria-hidden="true"></i> Show</a>
                    <a  class="btn btn-warning" href="{{ path('app_users_edit', {'id': user.id}) }}"><i class="fa fa-pencil fa-fw"></i> Edit</a>
                    <form method="post" action="{{ path('app_users_delete', {'id': user.id}) }}" style="display:
                    inline-block" onsubmit="return confirm('Êtes vous vraiment sûr ?')">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
                        <button class="btn btn-danger""><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_users_new') }}">Create new</a>

<script>
function searchTable() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("searchField");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
{% endblock %}

templates/users/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Users{% endblock %}

{% block body %}
    <h1>Create new Users</h1>
        


    {{ include('users/_form.html.twig') }}
   
{% endblock %}

templates/users/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block body %}
    <h1>Users</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ user.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ user.adresse }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ user.ville }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ user.codePostal }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ user.pays }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ user.etat }}</td>
            </tr>
            <tr>
                <th>Role</th>
                    <td>
                        {% for role in user.role %}
                            {{ role.nom }}
                        {% endfor %}
                    </td>
            </tr>


            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

   <a class="btn btn-primary btn-lg" href="{{ path('app_users_index') }}"><i class="fa fa-home"></i> back</a>

 <form method="post" action="{{ path('app_users_delete', {'id': user.id}) }}" style="display:
                    inline-block" onsubmit="return confirm('Êtes vous vraiment sûr ?')">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
                        <button class="btn btn-danger btn-lg"><i class="fa fa-trash " aria-hidden="true"></i> Delete</button>
                    </form>

    <a class="btn btn-warning  btn-lg" href="{{ path('app_users_edit', {'id': user.id}) }}"><i class="fa fa-pencil fa-fw"></i> Edit</a>

{% endblock %}